pipeline:
  name: CICD_Yuvaraj_App
  identifier: CICD_Yuvaraj_App
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: Yuvaraj_K_App
        build: <+input>
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: mvn clean install
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: Docker_Yuvaraj_K
                    repo: vinay1074/web_app
                    tags:
                      - latest
    - stage:
        name: Deploy
        identifier: Deploy
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: Kubernetes_Yuvaraj_K
          environment:
            environmentRef: Kubernetes_Environment
            deployToAll: false
            infrastructureDefinitions:
              - identifier: Kubernetes_INF_DEF_Yuvaraj_K
          execution:
            steps:
              - step:
                  type: K8sBlueGreenDeploy
                  name: K8sBlueGreenDeploy_1
                  identifier: K8sBlueGreenDeploy_1
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
                    skipUnchangedManifest: false
                  timeout: 10m
              - step:
                  type: K8sBGSwapServices
                  name: K8sBGSwapServices_1
                  identifier: K8sBGSwapServices_1
                  spec: {}
              - step:
                  type: K8sBlueGreenStageScaleDown
                  name: K8sBlueGreenStageScaleDown_1
                  identifier: K8sBlueGreenStageScaleDown_1
                  spec: {}
                  timeout: 10m
            rollbackSteps:
              - step:
                  name: Swap primary with stage service
                  identifier: rollbackBgSwapServices
                  type: K8sBGSwapServices
                  timeout: 10m
                  spec:
                    skipDryRun: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
