apiVersion: v1
kind: Service
metadata:
  name: simple-web
spec:
  selector:
    app: simple-web
  type: LoadBalancer
  ports:
    - name: simple-web
      protocol: TCP
      port: 80
      targetPort: 8080
