apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-web
  labels:
    app: simple-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-web
  template:
    metadata:
      labels:
        app: simple-web
    spec:
      containers:
      - image: 453411705158.dkr.ecr.us-east-1.amazonaws.com/web_app:3.0
        name: simple-web
        ports:
        - containerPort: 8080
